version: "3.4"

services:

  mutarr:
    build:
        context: .
        target: develop
    container_name: mutarr
    environment:
      - NODE_ENV=development
    env_file:
        - ./.env
    volumes:
      - /mutarr/lib/node_modules
      - ./:/mutarr/lib
      - ./tmp:/mutarr/tmp
      - ~/Videos:/mutarr/watch/videos
      # - tnas-shows:/mutarr/watch/shows
      # - tnas-movies:/mutarr/watch/movies
    command: npm run dev
    ports:
      - 3000:3000
      - 3001:3001

volumes:

  tnas-shows:
    driver_opts:
      type: nfs
      o: "addr=192.168.1.243,nolock,soft,rw,vers=4"
      device: ":/mnt/md0/media/shows"

  tnas-movies:
    driver_opts:
      type: nfs
      o: "addr=192.168.1.243,nolock,soft,rw,vers=4"
      device: ":/mnt/md0/media/movies"