version: "3.4"

services:
  mutarr:
    # image: saccodigital/mutarr:main
    build:
      context: .
      target: develop
    environment:
      - NODE_ENV=development
      - APP_NAME=mutarr
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TARGET_CODEC=h265
      - WORKER_CONCURRENCY=1
      - WATCH_ENABLED=true
      - MASTER=true
    volumes:
      - ./:/mutarr/lib
      - /mutarr/lib/node_modules
      - ~/Videos:/mutarr/watch/videos
      # - tnas-shows:/mutarr/watch/shows
      # - tnas-movies:/mutarr/watch/nfs-movies
      - tnas-videos:/mutarr/watch/nfs-videos
    command: npm run dev
    ports:
      - 3000:3000
    deploy:
      mode: replicated
      replicas: 1

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - 6378:6379
    restart: always

volumes:
  # tnas-shows:
  #   driver_opts:
  #     type: nfs
  #     o: "addr=192.168.1.243,nolock,soft,rw,vers=4"
  #     device: ":/mnt/md0/media/shows"

  # tnas-movies:
  #   driver_opts:
  #     type: nfs
  #     o: "addr=192.168.1.243,nolock,soft,rw,vers=4"
  #     device: ":/mnt/md0/media/movies"

  tnas-videos:
    driver_opts:
      type: nfs
      o: "addr=192.168.1.243,nolock,soft,rw,vers=4"
      device: ":/mnt/md0/media/videos"
